version: '2'
services:
#  redistest:
#    image: redis:4.0-alpine
#    ports:
#    - "6379:6379"
#  mongotest:
#    image: mongo:3.2
#    ports:
#    - "27017:27017"
  postgres:
    image: postgres:9-alpine
    environment:
      POSTGRES_USER: visitor
      POSTGRES_DB: gefenTests
    ports:
    - "5432:5432"
  rabbit-mq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  nats:
    # https://hub.docker.com/_/nats/
    image: nats
    ports:
    - 4222:4222
    - 8222:8222
    - 6222:6222

  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
